# dvc.yaml
stages:
  get_data:
    cmd: python src/get_data.py
    deps:
    - src/get_data.py
    outs:
    - data/raw
  preprocess:
    cmd: python src/preprocess.py
    deps:
    - src/preprocess.py
    - data/raw
    - params.yaml
    outs:
    - data/processed
  train:
    cmd: python src/train.py
    deps:
    - src/train.py
    - data/processed
    - params.yaml
    outs:
    - models
    - train_metrics
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - src/evaluate.py
    - models
    - data/processed
    metrics:
    - metrics/metrics.json:
        cache: false
metrics:
- metrics/metrics.json
plots:
- metrics/plots/metrics:
    x: step
