data:
  raw_dir: data/raw
  processed_dir: data/processed
  train_ratio: 0.8
features:
  scale: true
train:
  test_size: 0.2
  random_state: 42
  n_estimators: 200
  max_depth: 6
paths:
  model_dir: models
  metrics_dir: metrics
  train_metrics_dir: train_metrics
